import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/Banner";
import { Navbar } from "@/components/nav/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar username="adedayo@test.com" />
      <Banner
        title="Clifford the red dog"
        subtitle="a very cute movie"
        imgUrl="/static/clifford.webp"
      />
      {/* <NavBar/> */}
      {/* <Banner/> */}
      {/* <Card/> */}
    </div>
  );
}
