import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/Banner";
import { Navbar } from "@/components/nav/Navbar";
import Card from "@/components/card/Card";
import { SectionCards } from "@/components/card/SectionCards";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const disneyVideos = [
    {
      imgUrl: "/static/clifford.webp",
      size: "large",
      id: 0,
    },
    {
      imgUrl: "/static/clifford.webp",
      size: "large",
      id: 1,
    },
    {
      imgUrl: "/static/clifford.webp",
      size: "large",
      id: 2,
    },
    {
      imgUrl: "/static/clifford.webp",
      size: "large",
      id: 3,
    },
    {
      imgUrl: "/static/clifford.webp",
      size: "large",
      id: 4,
    },
    {
      imgUrl: "/static/clifford.webp",
      size: "large",
      id: 5,
    },
    {
      imgUrl: "/static/clifford.webp",
      size: "large",
      id: 6,
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar username="adedayo@test.com" />
      <Banner
        title="Clifford the red dog"
        subtitle="a very cute movie"
        imgUrl="/static/clifford.webp"
      />
      <div className={styles.sectionWrapper}>
        <SectionCards title="John Wick" videos={disneyVideos} size="large" />
        <SectionCards title="John Wick" videos={disneyVideos} size="medium" />
      </div>
    </div>
  );
}
